#  Code Neural Network From Scratch

In [1]:
# Only dependancy will be Numpy
import numpy as np
# Just for displaying images
from IPython.core.display import Image

# For displaying multiple variables in one cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

![Image of Neural Net](https://s3-ap-south-1.amazonaws.com/av-blog-media/wp-content/uploads/2017/05/29021937/635965173527052708-540999202_wallpaper-2870969.jpg)

## First Define the Activation Function

### Activation Function --> Sigmoid

![Image of Yaktocat](https://cdn-images-1.medium.com/max/1200/1*sK6hjHszCwTE8GqtKNe1Yg.png)

<h1><center>$ { f(x)=\frac{1}{1+e^{-x}} } $</center></h1>

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

![Derivitive of Sigmoid](https://i2.wp.com/kawahara.ca/wp-content/uploads/derivative_sigmoid.png?fit=430%2C339&ssl=1)

<h1><center>$ { f'(x)= f(x) (1 - f(x)) } $</center></h1>

In [3]:
def sigmoid_deriv(x):
    return x * (1 - x)

# One Perceptron, One Input & One Training Instance

Just a single percceptron with a single input and a single training example.

In [4]:
X = np.array([1])
y = np.array([1])

In [5]:
weight = 2 * np.random.random((1,1)) - 1

In [6]:
print("First Weight: ", weight[0][0])
print("First Prediction: ", sigmoid(np.dot(X, weight))[0])

for i in range(1000):
    
    # Get outputs (the prediction)
    guess = sigmoid(np.dot(X, weight))
    
    # See how much it's off by...
    error = y - guess
    
    # Get delta --> postitive OR negative (small change in weight(s)...)
    delta = error * sigmoid_deriv(guess)
    
    # Update the weight
    weight += np.dot(delta, X)

First Weight:  0.755362385006
First Prediction:  0.680346011642


In [7]:
print("Final Weight: ", weight[0][0])
print("Final Prediction: ", guess)

Final Weight:  3.73433524206
Final Prediction:  [ 0.97665619]


# One Perceptron, 3 Inputs & One Training Instance

![Single Perceptron](http://neuralnetworksanddeeplearning.com/images/tikz0.png)

In [8]:
X = np.array([[1,0,1]])
y = np.array([1])

In [9]:
weights = 2 * np.random.random((3,1)) - 1

In [10]:
print("First Weights: \n", weights)
print("\nFirst Prediction: \n", sigmoid(np.dot(X, weights)))

for i in range(1000):
    
    # Get outputs (the prediction)
    guess = sigmoid(np.dot(X, weights))
        
    # See how much it's off by...
    error = y - guess
        
    # Get delta --> postitive OR negative (small change in weight(s)...)
    delta = error * sigmoid_deriv(guess)
    
    # Update the weights
    weights += np.dot(X.T, delta)

First Weights: 
 [[-0.44249234]
 [ 0.98845667]
 [ 0.29813805]]

First Prediction: 
 [[ 0.46397397]]


In [11]:
print("Final Weights: \n", weights)
print("Final Prediction: \n", guess)

Final Weights: 
 [[ 1.67888664]
 [ 0.98845667]
 [ 2.41951703]]
Final Prediction: 
 [[ 0.98366345]]


<p><b><i><center>It doesn't change the middle weight at all because it's input is 0 and it has no effect anyway.</center></i></b></p>

# One Perceptron, Three Weights & Four Instances

![Derivitive of Sigmoid](https://cdn-images-1.medium.com/max/800/1*nEooKljI8XbKQh4cFbZu1Q.png)

In [12]:
X = np.array([[0,0,1], [1,1,1], [1,0,1], [0,1,1]])
y = np.array([[0,1,1,0]]).T

In [13]:
weights = 2 * np.random.random(((3,1))) - 1

## Train The Net

In [14]:
for _ in range(1000):
    
    # Make a guess for the instances
    guesses = sigmoid(np.dot(X, weights))
    
    error = y - guesses
    
    delta = error * sigmoid_deriv(guesses)
    
    weights += np.dot(X.T, delta)

In [15]:
weights

array([[ 7.25986187],
       [-0.22211738],
       [-3.41197415]])

In [16]:
guesses

array([[ 0.03194033],
       [ 0.97404837],
       [ 0.97910961],
       [ 0.025742  ]])

![Rocky Success](http://cdn5.thr.com/sites/default/files/2015/11/rocky_pub01_-_h_2015.jpg)

## What If We Change The Training Data?

In [17]:
# Change the training data to be an ??? relationship
X = np.array([[0,0,1], [1,1,1], [1,0,1], [0,1,1]])
y = np.array([[0,0,1,1]]).T

In [18]:
weights = 2 * np.random.random(((3,1))) - 1

In [19]:
for _ in range(1000):
    
    guesses = sigmoid(np.dot(X, weights))
    
    error = y - guesses
    
    delta = error * sigmoid_deriv(guesses)
    
    weights += np.dot(X.T, delta)

In [20]:
weights

array([[ -4.16333634e-16],
       [ -4.30211422e-16],
       [  5.41233725e-16]])

In [21]:
guesses

array([[ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5]])

![Broken Brain](https://orig12.deviantart.net/4c1f/f/2008/349/c/a/brain_is_broken_by_frotu.jpg)

<h1><center>Add A Hidden Layer To The Neural Net!</center></h1>

![Image of Yaktocat](https://cdn-images-1.medium.com/max/800/1*Qt5lealRQ29-R8rcTPDtoA.png)

# First With One Instance

In [22]:
X = np.array([[0,1,1]])
y = np.array([1]).T
X

array([[0, 1, 1]])

In [23]:
# Inputs by Perceptrons
weights1 = 2 * np.random.random((3,4)) - 1
weights2 = 2 * np.random.random((4,1)) - 1

In [24]:
weights1
weights2

array([[-0.62649681, -0.22127379, -0.91182886, -0.55851128],
       [ 0.67441677,  0.83457105, -0.74037208, -0.3850311 ],
       [ 0.24519566, -0.36643728,  0.43964514, -0.16255087]])

array([[-0.79858644],
       [-0.20000916],
       [ 0.93565978],
       [-0.98527273]])

In [25]:
for _ in range(1000):
    
    # ------------------------- Forward Propagation ---------------------------- #
    # Get predictions for layer 1 & 2
    layer1 = sigmoid(np.dot(X, weights1))
    layer2 = sigmoid(np.dot(layer1, weights2))
    
    # -------------------------- Back Propagation ------------------------------ #
    # Get errors from output (layer 2)
    layer2_error = y - layer2
    layer2_delta = layer2_error * sigmoid_deriv(layer2)
    
    # Get errors from layer1 (this part confuses me...)
    layer1_error = np.dot(layer2_delta, weights2.T)
    layer1_delta = layer1_error * sigmoid_deriv(layer1)

    # How much do we need to update the weights?
    weights1_update = np.dot(X.T, layer1_delta) 
    weights2_update = np.dot(layer1.T, layer2_delta)
    
    # Update the weights
    weights1 += weights1_update
    weights2 += weights2_update    

In [26]:
# Final Answer
layer2

array([[ 0.98469406]])

# Now With Four Instances

In [27]:
X = np.array([[0,0,1], [1,1,1], [0,1,1], [1,0,1]])
y = np.array([[0,0,1,1]]).T
X

array([[0, 0, 1],
       [1, 1, 1],
       [0, 1, 1],
       [1, 0, 1]])

In [28]:
# Inputs by Perceptrons
weights1 = 2 * np.random.random((3,4)) - 1
weights2 = 2 * np.random.random((4,1)) - 1

In [29]:
weights1
weights2

array([[ 0.24988307,  0.40120767,  0.3867602 ,  0.2562829 ],
       [ 0.14106874, -0.47063763, -0.614184  ,  0.64200734],
       [ 0.05946526, -0.21957399,  0.85599855, -0.18126844]])

array([[-0.24327279],
       [-0.77783789],
       [-0.60458831],
       [-0.33863808]])

In [30]:
for _ in range(50000):
    
    # ------------------------- Forward Propagation ---------------------------- #
    # Get predictions for layer 1 & 2
    layer1 = sigmoid(np.dot(X, weights1))
    layer2 = sigmoid(np.dot(layer1, weights2))
    
    # -------------------------- Back Propagation ------------------------------ #
    # Get errors from output (layer 2)
    layer2_error = y - layer2
    layer2_delta = layer2_error * sigmoid_deriv(layer2)
    
    # Get errors from layer1 (this part confuses me...)
    layer1_error = np.dot(layer2_delta, weights2.T)
    layer1_delta = layer1_error * sigmoid_deriv(layer1)

    # How much do we need to update the weights?
    weights1_update = np.dot(X.T, layer1_delta) 
    weights2_update = np.dot(layer1.T, layer2_delta)
    
    # Update the weights
    weights1 += weights1_update
    weights2 += weights2_update   

In [31]:
layer2

array([[ 0.00212817],
       [ 0.0054112 ],
       [ 0.99471908],
       [ 0.996359  ]])

![Joke](https://i.redd.it/5193db0avbey.jpg)

# Video Showing Original Example

# One Perceptron, One Input & One Training Instance

Just a single percceptron with a single input and a single training example.

In [158]:
X = np.array([1])
y = np.array([1])

In [159]:
weight = 2 * np.random.random((1,1)) - 1

In [160]:
print("First Weight: ", weight[0][0])
print("First Prediction: ", sigmoid(np.dot(X, weight))[0])

for i in range(1000):
    
    # Get outputs (the prediction)
    guess = sigmoid(np.dot(X, weight))
    
    # See how much it's off by...
    error = y - guess
    
    # Get delta --> postitive OR negative (small change in weight(s)...)
    delta = error * sigmoid_deriv(guess)
    
    # Update the weight
    weight += np.dot(delta, X)

First Weight:  -0.75165336976
First Prediction:  0.320461146608


In [161]:
print("Final Weight: ", weight[0][0])
print("Final Prediction: ", guess)

Final Weight:  3.72741631964
Final Prediction:  [ 0.97649777]
